In [24]:
# Dataset:
# - 489 samples and 4 columns.
# - 3 input features: RM, LSTAT and PTRATIO.
# - MEDV is the target variable.
# - RM = average number of rooms per dwelling.
# - LSTAT = percentage of lower-status population.
# - PTRATIO = pupil-teacher ratio.
# - MEDV = median value of owner-occupied homes in $1000s.

In [3]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "housing.csv"

df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,
                            "schirmerchad/bostonhoustingmlnd",
                            file_path)

/tmp/ipykernel_4539/4021432446.py:6: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,

Using Colab cache for faster access to the 'bostonhoustingmlnd' dataset.

In [4]:
df.head(5)

      RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

In [5]:
print(list(df.columns))
"""
RM = ROOMS
LSTAT = LOWER ECONOMY PEOPLE %
PTRATIO = STUDENTS TO TEACHERS RATIO
MEDV = MEDIAN VALUE OF HOUSE
"""

['RM', 'LSTAT', 'PTRATIO', 'MEDV']

In [9]:
print(df.dtypes,"\n",df.shape,"\n",df.info(),"\n",df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   RM       489 non-null    float64
 1   LSTAT    489 non-null    float64
 2   PTRATIO  489 non-null    float64
 3   MEDV     489 non-null    float64
dtypes: float64(4)
memory usage: 15.4 KB
RM         float64
LSTAT      float64
PTRATIO    float64
MEDV       float64
dtype: object
 (489, 4)
 None
                RM       LSTAT     PTRATIO          MEDV
count  489.000000  489.000000  489.000000  4.890000e+02
mean     6.240288   12.939632   18.516564  4.543429e+05
std      0.643650    7.081990    2.111268  1.653403e+05
min      3.561000    1.980000   12.600000  1.050000e+05
25%      5.880000    7.370000   17.400000  3.507000e+05
50%      6.185000   11.690000   19.100000  4.389000e+05
75%      6.575000   17.120000   20.200000  5.187000e+05
max      8.398000   37.970000   22.000000  1.024800e+06

In [11]:
df.isnull().sum()

RM         0
LSTAT      0
PTRATIO    0
MEDV       0
dtype: int64

In [13]:
int(df.duplicated().sum())

0

In [15]:
X = df.drop("MEDV",axis=1)
y = df["MEDV"]

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test  = train_test_split(X,y,random_state=42,test_size=0.2)

In [18]:
from sklearn.linear_model import LinearRegression

model  = LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [22]:
from sklearn.metrics import mean_absolute_error, mean_squared_error , r2_score

import numpy as np

print("MAE : ", mean_absolute_error(y_test,y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R²:", r2_score(y_test, y_pred))

MAE :  64277.28865670341
RMSE: 82395.54332162566
R²: 0.691093400309851